### ISSUE TITLE
Some final roadblocks that I need to get over to get this fully working

### ISSUE THREAD

**Issue by emaxsaun** [yahoo/protractor-retry#12]
Hi Again :)

I am not sure if this is something that is specific to my config, or if this is something you guys can help with, but I've been banging my head against the wall trying to get the last part of this fully working before we can use it :) 

So basically, we run our Protractor tests in Jenkins, and with the help from you guys, I was able to get the retry working properly with suites, and get the retry working in Jenkins, which is awesome! :) Thank you again for helping solve those issues. 

But, as always with this stuff, it's one step forward, one step back.

Now when the build runs in Jenkins, two things happen:

1) I am using the following reporter - protractor-jasmine2-screenshot-reporter - https://www.npmjs.com/package/protractor-jasmine2-screenshot-reporter, and this reporter is great, but when I use this with protractor-retry, in Jenkins, the report created is only the last (failed) scenario. Ideally I would like this to have a first run report, and then a retry report fail. Right now there is just one report with the failed test.

2) The second issue, is that even though the retried test fails, Jenkins still marks the build as successful, which is not correct. If the tests fail, Jenkins should mark the build as a failure, it does this when not using protractor-retry.

Do you guys have any ideas here? I can share some parts of my Jenkins config if that will help. Thanks!

**Comment by amrot17** [comment]
Hi ,

I think that this behavior is due to the data the already generated from the reporter during the execution before the retry 

my advice is to find a way to delete/move all files related to the specs that will be re executed with the retry module 

you can apply that on the afterLaunch() function and you can use the data on the report file that the retry is using 

thanks

**Comment by emaxsaun** [comment]
Hi,

Ah, I see. I will try to mess with this and see if I can get this working that way! Thank you!

Thanks!

**Comment by emaxsaun** [comment]
Hi Again.

Okay, so what I did to debug this, was I removed the step in my Jenkins config for `Publish HTML reports`

I went into my `protractor.conf.js` file and commented out where I am using the `protractor-jasmine2-screenshot-reporter`

So now the reporter is not being used at all.

I ran a suite of tests called flake, with one test that passes, and one test that fails, but I am still getting Jenkins marking the build as success. 

Here is the complete log from Jenkins below.

I don't know why this would mark the build as successful in Jenkins, because the test is clearly failing on retry. I am excepting Jenkins to report `Finished: FAILURE`

Do you have any ideas? Thanks again.

```
[EnvInject] - Loading node environment variables.
Building remotely on build-qa (i-09619477e84471392) (qa) in workspace /opt/jenkins_slave/workspace/Protractor Automation Tests
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git rev-parse refs/remotes/origin/changes/11/44311/13^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/changes/11/44311/13^{commit} # timeout=10
Checking out Revision 2ce22601cc17b39ad31366024ae834b5622c92ff (refs/remotes/origin/changes/11/44311/13)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 2ce22601cc17b39ad31366024ae834b5622c92ff
Commit message: "Retry for Protractor WIP"
First time build. Skipping changelog.
No emails were triggered.
Xvfb starting$ Xvfb :101 -screen 0 1280x1024x16 -fbdir /opt/jenkins_slave/xvfb-151-5384419015197132271.fbdir
Set build name.
[Protractor Automation Tests] $ /usr/bin/env bash /tmp/jenkins3572629275995293848.sh
Removing node_modules/
Removing protractorFailuresReport/
v8.1.2
5.0.3

> phantomjs@2.1.7 install /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1510250739733/phantomjs-2.1.1-linux-x86_64 -> /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/phantomjs/lib/phantom/bin/phantomjs

> fsevents@1.1.2 install /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/fsevents
> node install

npm WARN protractor-testing@ No repository field.
npm WARN protractor-testing@ No license field.

added 1168 packages in 18.697s

> chromedriver@2.33.2 install /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip
Saving to /tmp/chromedriver/chromedriver_linux64.zip
Received 781K...
Received 1568K...
Received 2352K...
Received 3136K...
Received 3920K...
Received 3995K total.
Extracting zip contents
Copying to target path /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/chromedriver/lib/chromedriver/chromedriver
npm WARN protractor-testing@ No repository field.
npm WARN protractor-testing@ No license field.

+ chromedriver@2.33.2
added 22 packages in 4.379s
webdriver-manager: using local installed version 12.0.4
[18:05:49] I/file_manager - creating folder /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/webdriver-manager/selenium
[18:05:49] I/downloader - curl -o /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/webdriver-manager/selenium/chromedriver_2.32.zip https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip
[18:05:49] I/downloader - curl -o /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.7.1.jar https://selenium-release.storage.googleapis.com/3.7/selenium-server-standalone-3.7.1.jar
[18:05:49] I/update - chromedriver: unzipping chromedriver_2.32.zip
[18:05:50] I/update - chromedriver: setting permissions to 0755 for /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/webdriver-manager/selenium/chromedriver_2.32
[18:05:50] I/downloader - curl -o /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/webdriver-manager/selenium/geckodriver-v0.19.1.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
[18:05:50] I/update - geckodriver: unzipping geckodriver-v0.19.1.tar.gz
[18:05:50] I/update - geckodriver: setting permissions to 0755 for /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/webdriver-manager/selenium/geckodriver-v0.19.1
(node:1492) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[18:05:50] I/launcher - Running 1 instances of WebDriver
....[18:06:06] I/testLogger - 
------------------------------------

[18:06:06] I/testLogger - [chrome #01-0] PID: 1498
[chrome #01-0] Specs: /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/ny-regressions/tests/logInHeader.js
[chrome #01-0] 
[chrome #01-0] (node:1498) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[chrome #01-0] [18:05:51] I/local - Starting selenium standalone server...
[chrome #01-0] [18:05:51] I/local - Selenium standalone server started at http://10.0.16.190:52554/wd/hub
[chrome #01-0] Started
[chrome #01-0] ....
[chrome #01-0] 
[chrome #01-0] 
[chrome #01-0] 4 specs, 0 failures
[chrome #01-0] Finished in 12.744 seconds
[chrome #01-0] 
[chrome #01-0] [18:06:06] I/local - Shutting down selenium standalone server.

[18:06:06] I/testLogger - 

[18:06:06] I/launcher - 1 instance(s) of WebDriver still running
....F.[18:06:33] I/testLogger - 
------------------------------------

[18:06:33] I/testLogger - [chrome #01-1] PID: 1673
[chrome #01-1] Specs: /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/ny-regressions/tests/checkListingsNumber.js
[chrome #01-1] 
[chrome #01-1] (node:1673) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[chrome #01-1] [18:06:06] I/local - Starting selenium standalone server...
[chrome #01-1] [18:06:07] I/local - Selenium standalone server started at http://10.0.16.190:45670/wd/hub
[chrome #01-1] Started
[chrome #01-1] ....F.
[chrome #01-1] 
[chrome #01-1] Failures:
[chrome #01-1] 1) checkListingsNumber should verify the total number of the listings as logged in user
[chrome #01-1]   Message:
[chrome #01-1]     Expected 10050 to be greater than 30000.
[chrome #01-1]   Stack:
[chrome #01-1]     Error: Failed expectation
[chrome #01-1]         at /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/ny-regressions/tests/checkListingsNumber.js:47:55
[chrome #01-1]         at elementArrayFinder_.then (/opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/protractor/lib/element.ts:840:22)
[chrome #01-1]         at ManagedPromise.invokeCallback_ (/opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/selenium-webdriver/lib/promise.js:1366:14)
[chrome #01-1]         at TaskQueue.execute_ (/opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/selenium-webdriver/lib/promise.js:2970:14)
[chrome #01-1]         at TaskQueue.executeNext_ (/opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/selenium-webdriver/lib/promise.js:2953:27)
[chrome #01-1]         at asyncRun (/opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/selenium-webdriver/lib/promise.js:2813:27)
[chrome #01-1]         at /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/selenium-webdriver/lib/promise.js:676:7
[chrome #01-1]         at <anonymous>
[chrome #01-1]         at process._tickCallback (internal/process/next_tick.js:169:7)
[chrome #01-1] 
[chrome #01-1] 6 specs, 1 failure
[chrome #01-1] Finished in 23.419 seconds
[chrome #01-1] 
[chrome #01-1] [18:06:32] I/local - Shutting down selenium standalone server.

[18:06:33] I/testLogger - 

[18:06:33] I/launcher - 0 instance(s) of WebDriver still running
[18:06:33] I/launcher - chrome #01-0 passed
[18:06:33] I/launcher - chrome #01-1 failed 1 test(s)
[18:06:33] I/launcher - overall: 1 failed spec(s)


 Re-running tests , attempt :  1
 Re-running the following test files : /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/ny-regressions/tests/checkListingsNumber.js


(node:1871) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[18:06:33] I/launcher - Running 1 instances of WebDriver
[18:06:33] I/local - Starting selenium standalone server...
[18:06:34] I/local - Selenium standalone server started at http://10.0.16.190:54279/wd/hub
Started
....F.

Failures:
1) checkListingsNumber should verify the total number of the listings as logged in user
  Message:
    Expected 10050 to be greater than 30000.
  Stack:
    Error: Failed expectation
        at /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/ny-regressions/tests/checkListingsNumber.js:47:55
        at elementArrayFinder_.then (/opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/protractor/lib/element.ts:840:22)
        at ManagedPromise.invokeCallback_ (/opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:169:7)

6 specs, 1 failure
Finished in 20.128 seconds

[18:06:56] I/local - Shutting down selenium standalone server.
[18:06:56] I/launcher - 0 instance(s) of WebDriver still running
[18:06:56] I/launcher - chrome #01 failed 1 test(s)
[18:06:56] I/launcher - overall: 1 failed spec(s)
[18:06:56] E/launcher - Process exited with error code 1
Set build name.
Xvfb stopping
Email was triggered for: Success
Sending email for trigger: Success
Finished: SUCCESS
```

**Comment by amrot17** [comment]
HI ,
as Protractor is finished with `Process exited with error code 1` 
this should definitely fail the build 

I did some research about this issue , and below is the best that can describe what may happened with your job.

https://stackoverflow.com/questions/32056124/jenkins-return-job-status-success-when-the-test-failed

hope that this help you find the issue 

thanks

**Comment by emaxsaun** [comment]
Thanks, I will look into this, but it is very weird, because when I run my Jenkins job without protractor-retry and I have any test failures, with plain protractor, the Jenkins build fails as it should.

**Comment by emaxsaun** [comment]
I wanted to update you guys here, after upgrading to the latest version, this is fixed.
