### ISSUE TITLE
Exit with Error code 199 when using protractor retry

### ISSUE THREAD

**Issue by christineedwards** [yahoo/protractor-retry#13]
Hi,
I looks like it does try to re-run the test but I am getting the following error.  There is more to the error if you need to see it let me know.  Any help would be greatly appreciated.

[12:14:36] E/launcher - spawn C:\Users\cedwar17\AppData\Roaming\npm\node_modules\protractor\bin\protractor ENOENT
[12:14:36] E/launcher - Error: spawn C:\Users\cedwar17\AppData\Roaming\npm\node_modules\protractor\bin\protractor ENOENT
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
[12:14:36] E/launcher - Process exited with error code 199

Christine

**Comment by dreuxl** [comment]
Hi,

Thanks for using our pkg. let s try to figure out your pb :) . few questions:

* What is the tool that you are using to run protractor?
* What is the protractor Command Line generated?
* Can you provide a gist of the whole output of your run?

thanks,
Ludo

**Comment by christineedwards** [comment]
HI.  Thank you for the quick response and retry package.

When receiving this error I am executing the test in visual code with the following command
node index.js run e2e --suite=singleton --testonly --skipData
It looks like the command line generated is:
protractor testing/e2e/protractor.config.LOCAL.js --suite singleton

I have never created a gist file before.  Let me know if this works
<script src="https://gist.github.com/christineedwards/fb76a76af118dbb9cc4333fdd81bedf0.js"></script> 

Thank you for the help
Christine

**Comment by dreuxl** [comment]
this link https://gist.github.com/christineedwards/fb76a76af118dbb9cc4333fdd81bedf0 
is perfect :)

ok it seems similar to https://github.com/yahoo/protractor-retry/issues/8
there is a PATH issue somewhere and protractor binary is not found any more on the retry.

Can you somehow try to add a DEBUG param in your node CLI in order to get more information, to get something like :

```
DEBUG=ProtractorRetry ./node_modules/.bin/protractor protractor.conf.js
```

thanks

**Comment by christineedwards** [comment]
I don't know how to add a DEBUG param to my node CLI.  Are you saying to add this directly into the node_modules CLI file?
Thanks,
Christine

**Comment by dreuxl** [comment]
try a

```
DEBUG=ProtractorRetry node index.js run e2e --suite=singleton --testonly --skipData
```

**Comment by christineedwards** [comment]
Sorry I am relatively new to this.  Appreciate the help.  Here is the new output

<script src="https://gist.github.com/christineedwards/b4b0e329ec6de6fec6a7a6e34f8fcac1.js"></script>
Christine

**Comment by christineedwards** [comment]
Hi,  Were you able to read the gist I attached to the previous message?
Christine

**Comment by dreuxl** [comment]
Yeah, I was.

Look like you run your script under windows, we never try that. I have to try on my side and see.

**Comment by christineedwards** [comment]
Hi,
Were you able to figure anything out with this?

Thank you,
Christine

**Comment by dreuxl** [comment]
Not yet have a chance to try/reproduce it on a windows machine :(. I ll keep u posted.

**Comment by ajaysuwalka** [comment]
Please take this on priority if possible I am also looking out for solution to this

**Comment by christineedwards** [comment]
Hi,
Have you had a chance to look at this?  I have been trying to figure it out also, but am at a loss.  
I have also tried to run it in our sauce-labs environment thinking that maybe it was my local environment but I get the same results.
Thank You,
Christine

**Comment by dreuxl** [comment]
hey Christine, 

couple of questions

* Where is located the `protractor` binary on your windows?
* What is the current folder where you launch your Command Line? Can you list me the current folder?
* Is this path correct for you and that s where us expect your protractor binary to be? `C:\Users\cedwar17\AppData\Roaming\npm\node_modules\protractor\bin\protractor`

**Comment by dreuxl** [comment]
ok so it maybe because we are using `$0` as a var to detect the Command played initially and this has no meaning on windows batch, which only recognize `%0` according to
https://superuser.com/questions/131777/windows-7-command-line-variable-equivalent-to-0

meaning that so far running the `protractor-retry` on windows machine is not yet supported :(. I need to find a solution

**Comment by stemkar123** [comment]
Hi,
I was facing same issue "Exit with Error code 199". And I have installed the crossSpawn as well & done the required changes in json file & retry file. Now I am getting below error:

[17:39:46] E/launcher - Error: TypeError: value.apply is not a function
at Promise.apply (D:\Reposirtory\test\ui\node_modules\q\q.js:1185:26)
at Promise.promise.promiseDispatch (D:\Reposirtory\test\ui\node_modules\q\q.js:808:41)
at D:\Reposirtory\test\ui\node_modules\q\q.js:1411:14
at runSingle (D:\Reposirtory\test\ui\node_modules\q\q.js:137:13)
at flush (D:\Reposirtory\test\ui\node_modules\q\q.js:125:13)
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickCallback (internal/process/next_tick.js:180:9)
[17:39:46] E/launcher - Process exited with error code 1

**Comment by amrot17** [comment]
@stemkar123  we did some fixes in the latest published version , please check if this fixed your issue

**Comment by krthknan** [comment]
protractor-retry on windows machine is supported??
