### ISSUE TITLE
TypeError: "file" argument must be a non-empty string

### ISSUE THREAD

**Issue by stemkar123** [yahoo/protractor-retry#17]
I am using Protractor for automation. Actually I need to rerun the failed test cases so I used protractor-retry. But while execution I am getting "TypeError: "file" argument must be a non-empty string" error & failed cases are not re-executed.

below is my conf & spec file:

**Sample.conf:**
var retry = require('protractor-retry').retry;

exports.config = {
 specs: ['sampleCase.js'],
onCleanUp: function (results) {
        retry.onCleanUp(results);
    },
   
   onPrepare: function () {
			retry.onPrepare();
   },
      
    afterLaunch: function() {
        return retry.afterLaunch(3);
    }	
  
};

**Sample.spec**
describe('Enter GURU99 Name', function() {
 it('should add a Name as GURU99', function() {
 browser.get('https://angularjs.org');
 element(by.model('yourName')).sendKeys('GURU99');
  var guru= element(by.xpath('html/body/div[2]/div[1]/div[2]/div[2]/div/h1'));
expect(guru.getText()).toEqual('Hello GURU99111!');
  });
});

**Error logs**
 Error: TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:380:11)
    at Object.exports.spawn (child_process.js:487:38)

Please assist

**Comment by dreuxl** [comment]
hi

* What is the OS you are using? if windows, i m still working on windows support but for now not yet supported.
* If you are running on Mac or Unix, can u please provide a console output gist of your run in order to try to repro.

Thanks

**Comment by stemkar123** [comment]
@dreuxl I am using Windows10. Please let know once you got the solution for windows

**Comment by dreuxl** [comment]
https://github.com/yahoo/protractor-retry/pull/16 WIP

**Comment by ngaruko** [comment]
I am having the same issue on Mac? ``` E/launcher - Error: TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:383:11)
    at Object.exports.spawn (child_process.js:496:38)```
Error comes when trying to re-run the failed spec..

**Comment by bishnupanda93** [comment]
Can someone please let me know if the solution for windows is ready.
