### ISSUE TITLE
Cannot read property 'specs' of undefined

### ISSUE THREAD

**Issue by ammargalal** [yahoo/protractor-retry#18]
Hi while running my configuration file after all spec is executed i get this error message i.e.

[16:08:54] I/local - Shutting down selenium standalone server.
[16:08:54] E/launcher - Error: TypeError: Cannot read property 'specs' of undefined
    at prepareData (D:\Choice_Workspace\Codes\QA\choice-hotels-js\node_modules\protractor-retry\lib\retry.js:170:48)
    at writeToFile (D:\Choice_Workspace\Codes\QA\choice-hotels-js\node_modules\protractor-retry\lib\retry.js:154:15)
    at Object.onCleanUp (D:\Choice_Workspace\Codes\QA\choice-hotels-js\node_modules\protractor-retry\lib\retry.js:117:9)
    at onCleanUp (D:\Choice_Workspace\Codes\QA\choice-hotels-js\src\test\resources\protractor-conf.js:104:15)
    at q_1.Promise (C:\Users\a.galal\AppData\Roaming\npm\node_modules\protractor\built\util.js:46:49)
    at Function.promise (C:\Users\a.galal\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:682:9)
    at Object.runFilenameOrFn_ (C:\Users\a.galal\AppData\Roaming\npm\node_modules\protractor\built\util.js:38:16)
    at Runner.exit_ (C:\Users\a.galal\AppData\Roaming\npm\node_modules\protractor\built\runner.js:35:27)
    at q.then.then.then.then.then.then.then.then.then (C:\Users\a.galal\AppData\Roaming\npm\node_modules\protractor\built\runner.js:437:25)
    at _fulfilled (C:\Users\a.galal\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
Closing report
[16:08:54] E/launcher - Process exited with error code 100

**Comment by tymfear** [comment]
Looks like you restart your browser at some point. When the browser is restarted the `browser.currentSpec` object is removed (looks like some issue with protractor).
My workaround was the following
```typescript
export async function restartBrowser(browserInstance: ProtractorBrowser = browser,
                                     waitForAngularEnabled: boolean = false): Promise<ProtractorBrowser> {

    const currentSpec: any = browser.currentSpec;

    await browser.restart();
    browser.currentSpec = currentSpec;
    await browser.waitForAngularEnabled(waitForAngularEnabled);

    return browserInstance;
}
```
