### ISSUE TITLE
I am trying to use Protractor retry, but its failed e2e file is not running

### ISSUE THREAD

**Issue by Rama9594** [yahoo/protractor-retry#27]
C:\Users\rs\Documents\potractorRetry>npm run e2e
> quote-builder-protractor@1.0.0 pree2e C:\Users\rs\Documents\potractorRetry
> npm run webdriver:update -- --standalone

> quote-builder-protractor@1.0.0 webdriver:update C:\Users\rs\Documents\potractorRetry
> npm run webdriver-manager update "--standalone"

> quote-builder-protractor@1.0.0 webdriver-manager C:\Users\rs\Documents\potractorRetry
> webdriver-manager "update"

[11:54:36] I/update - chromedriver: file exists C:\Users\rs\Documents\potractorRetry\node_modules\webdriver-manager\selenium\chromedriver_2.35.zip
[11:54:36] I/update - chromedriver: unzipping chromedriver_2.35.zip
[11:54:36] I/update - chromedriver: chromedriver_2.35.exe up to date
[11:54:36] I/update - selenium standalone: file exists C:\Users\rs\Documents\potractorRetry\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.9.1.jar
[11:54:36] I/update - selenium standalone: selenium-server-standalone-3.9.1.jar up to date
[11:54:39] I/update - geckodriver: file exists C:\Users\rs\Documents\potractorRetry\node_modules\webdriver-manager\selenium\geckodriver-v0.19.1.zip
[11:54:39] I/update - geckodriver: unzipping geckodriver-v0.19.1.zip
[11:54:39] I/update - geckodriver: geckodriver-v0.19.1.exe up to date

> quote-builder-protractor@1.0.0 e2e C:\Users\rs\Documents\potractorRetry
> npm run protractor

> quote-builder-protractor@1.0.0 protractor C:\Users\rs\Documents\potractorRetry
> protractor --directConnect

root directory: C:\Users\rs\Documents\potractorRetry

(node:9628) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[11:54:41] W/driverProviders - Using driver provider directConnect, but also found extra driver provider parameter(s): seleniumAddress
[11:54:41] I/launcher - Running 1 instances of WebDriver
[11:54:41] I/direct - Using ChromeDriver directly...

DevTools listening on ws://127.0.0.1:12794/devtools/browser/6bb41721-715a-47f1-bc94-610dd24daca7
Started
Attaching Default Reporter
.FF

Failures:
1) It block 1
  Message:
    Failed: No element found using locator: By(css selector, .sectionTabLabel.selected)
  Stack:
    NoSuchElementError: No element found using locator: By(css selector, .sectionTabLabel.selected)
        at elementArrayFinder.getWebElements.then (C:\Users\rs\Documents\potractorRetry\node_modules\protractor\lib\element.ts:851:17)
        at ManagedPromise.invokeCallback_ (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:1366:14)
        at TaskQueue.execute_ (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:2970:14)
        at TaskQueue.executeNext_ (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:2953:27)
        at asyncRun (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:2813:27)
        at C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)Error
        at ElementArrayFinder.applyAction_ (C:\Users\rs\Documents\potractorRetry\node_modules\protractor\lib\element.ts:482:23)
        at ElementArrayFinder.(anonymous function).args [as getText] (C:\Users\rs\Documents\potractorRetry\node_modules\protractor\lib\element.ts:96:21)
        at ElementFinder.(anonymous function).args [as getText] (C:\Users\rs\Documents\potractorRetry\node_modules\protractor\lib\element.ts:873:14)
        at errorArray.forEach.element (C:\Users\rs\Documents\potractorRetry\tests\QubyProtractorUtils\QubyProtractorUtils.ts:335:49)
        at Array.forEach (<anonymous>)
        at C:\Users\rs\Documents\potractorRetry\tests\QubyProtractorUtils\QubyProtractorUtils.ts:334:36
        at ManagedPromise.invokeCallback_ (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:1366:14)
        at TaskQueue.execute_ (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:2970:14)
        at TaskQueue.executeNext_ (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:2953:27)
        at asyncRun (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:2813:27)
    From: Task: Run it("Create Quote and verify the required fields") in control flow
        at UserContext.<anonymous> (C:\Users\rs\Documents\potractorRetry\node_modules\jasminewd2\index.js:94:19)
    From asynchronous test:
    Error
        at Suite.<anonymous> (C:\Users\rs\Documents\potractorRetry\tests\e2e\RegressionTests\Testing.e2e.ts:29:5)
        at Object.<anonymous> (C:\Users\rs\Documents\potractorRetry\tests\e2e\RegressionTests\Testing.e2e.ts:18:1)
        at Module._compile (module.js:635:30)
        at Module.m._compile (C:\Users\rs\Documents\potractorRetry\node_modules\ts-node\src\index.ts:382:23)
        at Module._extensions..js (module.js:646:10)
        at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\rs\Documents\potractorRetry\node_modules\ts-node\src\index.ts:385:12)

2) It block 2
  Message:
    Failed: No element found using locator: By(css selector, .sectionTabLabel.selected)
  Stack:
    NoSuchElementError: No element found using locator: By(css selector, .sectionTabLabel.selected)
        at elementArrayFinder.getWebElements.then (C:\Users\rs\Documents\potractorRetry\node_modules\protractor\lib\element.ts:851:17)
        at ManagedPromise.invokeCallback_ (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:1366:14)
        at TaskQueue.execute_ (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:2970:14)
        at TaskQueue.executeNext_ (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:2953:27)
        at asyncRun (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:2813:27)
        at C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)Error
        at ElementArrayFinder.applyAction_ (C:\Users\rs\Documents\potractorRetry\node_modules\protractor\lib\element.ts:482:23)
        at ElementArrayFinder.(anonymous function).args [as getText] (C:\Users\rs\Documents\potractorRetry\node_modules\protractor\lib\element.ts:96:21)
        at ElementFinder.(anonymous function).args [as getText] (C:\Users\rs\Documents\potractorRetry\node_modules\protractor\lib\element.ts:873:14)
        at errorArray.forEach.element (C:\Users\rs\Documents\potractorRetry\tests\QubyProtractorUtils\QubyProtractorUtils.ts:335:49)
        at Array.forEach (<anonymous>)
        at C:\Users\rs\Documents\potractorRetry\tests\QubyProtractorUtils\QubyProtractorUtils.ts:334:36
        at ManagedPromise.invokeCallback_ (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:1366:14)
        at TaskQueue.execute_ (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:2970:14)
        at TaskQueue.executeNext_ (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:2953:27)
        at asyncRun (C:\Users\rs\Documents\potractorRetry\node_modules\selenium-webdriver\lib\promise.js:2813:27)
    From: Task: Run it("switch to product and service page and Add favourite catalog products") in control flow
        at UserContext.<anonymous> (C:\Users\rs\Documents\potractorRetry\node_modules\jasminewd2\index.js:94:19)
    From asynchronous test:
    Error
        at Suite.<anonymous> (C:\Users\rs\Documents\potractorRetry\tests\e2e\RegressionTests\Testing.e2e.ts:46:5)
        at Object.<anonymous> (C:\Users\rs\Documents\potractorRetry\tests\e2e\RegressionTests\Testing.e2e.ts:18:1)
        at Module._compile (module.js:635:30)
        at Module.m._compile (C:\Users\rs\Documents\potractorRetry\node_modules\ts-node\src\index.ts:382:23)
        at Module._extensions..js (module.js:646:10)
        at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\rs\Documents\potractorRetry\node_modules\ts-node\src\index.ts:385:12)

3 specs, 2 failures
Finished in 24.515 seconds

Testing.e2e.ts-chrome
[11:55:09] I/launcher - 0 instance(s) of WebDriver still running
[11:55:09] I/launcher - chrome #01 failed 2 test(s)
[11:55:09] I/launcher - overall: 2 failed spec(s)

 Re-running tests , attempt :  1
 Re-running the following test files : C:\Users\rs\Documents\potractorRetry\tests\e2e\RegressionTests\Testing.e2e.ts

[11:55:09] E/launcher - spawn node_modules\protractor\bin\protractor ENOENT
[11:55:09] E/launcher - Error: spawn node_modules\protractor\bin\protractor ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[11:55:09] E/launcher - Process exited with error code 199
npm ERR! code ELIFECYCLE
npm ERR! errno 199
npm ERR! quote-builder-protractor@1.0.0 protractor: `protractor --directConnect`
npm ERR! Exit status 199
npm ERR!
npm ERR! Failed at the quote-builder-protractor@1.0.0 protractor script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rs\AppData\Roaming\npm-cache\_logs\2018-02-24T06_25_10_223Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 199
npm ERR! quote-builder-protractor@1.0.0 e2e: `npm run protractor`
npm ERR! Exit status 199
npm ERR!
npm ERR! Failed at the quote-builder-protractor@1.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rs\AppData\Roaming\npm-cache\_logs\2018-02-24T06_25_10_349Z-debug.log

**Comment by dreuxl** [comment]
Hi

thanks for using our pkg.
questions.
`[11:55:09] E/launcher - Error: spawn node_modules\protractor\bin\protractor ENOENT
at _errnoException (util.js:1024:11)` make me think you are using it from a windows machine, is that the case?

if it is, unfortunately, windows is not yet supported as a launcher. 
Other issues on this project has been reported for the same. stay tuned.

Thanks

**Comment by daBishMan** [comment]
@dreuxl any idea on when windows will be supported.

**Comment by dreuxl** [comment]
Nope :(

I found a windows laptop recently, will try to set up / repro and fix.
but no ETA atm

**Comment by smajazayeri** [comment]
It's a need for me too. Thanks for providing such a valuable lib. Looking forward to hearing from you soon.

**Comment by smajazayeri** [comment]
Any progress yet?

**Comment by dreuxl** [comment]
nope :( 

I have a WIP PR open here https://github.com/yahoo/protractor-retry/pull/16 . 
but it's not OK yet

**Comment by charan69** [comment]
Hi,

Any update on this? i still see this issue with retry

**Comment by sudeeppaudyal** [comment]
Any update on this?I have been trying to use protractor-retry.There is no any compile error but its not rerunning the failed test.Pls help.

**Comment by venkyramamoorthy** [comment]
Any update on Protractor Retry working in windows machine. Still facing the same issues.
Kindly help.
