### ISSUE TITLE
Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by rafalf** [yahoo/protractor-retry#36]
Env: Windows 10

```
[15:27:07] I/launcher - chrome #01 failed 2 test(s)
[15:27:07] I/launcher - overall: 2 failed spec(s)


 Re-running tests , attempt :  1
 Re-running the following test files : D:\xyz\test\versions.spec.js


[15:27:07] E/launcher - Error: { Error: spawn UNKNOWN
    at exports._errnoException (util.js:1020:11)
    at ChildProcess.spawn (internal/child_process.js:328:11)
    at Object.exports.spawn (child_process.js:369:9)
    at D:\xyz\node_modules\protractor-retry\lib\retry.js:151:38
    at Function.promise (D:\xyz\node_modules\q\q.js:702:9)
    at D:\xyz\node_modules\protractor-retry\lib\retry.js:150:18
    at Promise.apply (D:\xyz\node_modules\q\q.js:1185:26)
    at Promise.promise.promiseDispatch (D:\xyz\node_modules\q\q.js:808:41)
    at D:\xyz\node_modules\q\q.js:1411:14
    at runSingle (D:\xyz\node_modules\q\q.js:137:13) code: 'UNKNOWN', errno: 'UNKNOWN', syscall: 'spawn' }
[15:27:07] E/launcher - Process exited with error code 1
```

my config file

```
const Config = require('./config.data.json');
const path   = require('path');
const retry  = require('protractor-retry').retry;

const downloaddPath = path.resolve(__dirname, 'download')

let App = Config.apps[Object.keys(Config.apps)[0]];
let chromOpt = {
    args: [
            '--disable-infobars',
            '--window-size=1440,900'
        ],
    prefs: {'credentials_enable_service': false,
        download: {
            'prompt_for_download': false,
            'directory_upgrade': true,
            'default_directory': downloaddPath
        }
    } ,
};
let colours = true;


const init = function() {
  for (let i = 0; i < process.argv.length; i++) {
    const obj = process.argv[i];

    const appMatch = obj.match(/^--app=(.*)$/);
    if (appMatch && appMatch.length > 0) {
        App = Config.apps[appMatch[1]];
    }

    const headLessMatch = obj.match(/^--headless(.*)$/);
    if (headLessMatch && headLessMatch.length > 0) {

        console.log('browser Mode: headless');
        chromOpt = {
            args: [
                '--disable-infobars',
                '--window-size=1440,900',
                '--headless',
                '--no-sandbox',
                '--disable-gpu'
            ],
            prefs: {
                'credentials_enable_service': false,
                download: {
                    'prompt_for_download': false,
                    'directory_upgrade': true,
                    'default_directory': downloaddPath
                }
            },
        }
    }

    const coloursMatch = obj.match(/^--no-colours(.*)$/);
    if (coloursMatch && coloursMatch.length > 0) {
        console.log('colour mode: --no-colours');
        colours = false;
    }
  }
}();

exports.config = {

    directConnect: true,

    baseUrl: App.baseUrl,
    params: App.params,

    capabilities: {
        browserName: 'chrome',
		chromeOptions: chromOpt,
		loggingPrefs: {
			browser: 'ALL' // "OFF", "SEVERE", "WARNING", "INFO", "CONFIG", "FINE", "FINER", "FINEST", "ALL".
		},
        // allows different specs to run in parallel.
        // shardTestFiles: 'true',
        // maxInstances: 1
    },

    framework: 'jasmine',

    suites: {
        dev: ['./test/versions.spec.js'],
        smoke: [
            './test/validation.spec.js',
            './test/upload.spec.js',
            './test/folder.spec.js',
            './test/versions.spec.js',
            './test/search.spec.js',
            './test/archive.spec.js',
            './test/move.spec.js',
            './test/copy.spec.js',
            './test/tags.spec.js',
            './test/share.spec.js',
            './test/signup.spec.js',
            './test/secure.spec.js',
            './test/settings.spec.js',
            './test/share.users.spec.js',
        ],
        forked: [
            './test/forked/devices.spec.js'
        ],
        multiAccounts: [
            './test/setup/multi.accounts.spec.js'
        ],
        setup: [
            './test/setup/auto.accounts.spec.js'
        ],

    },

    // Before performing any action, Protractor waits until there are no pending asynchronous tasks in your Angular
    // application. This means that all timeouts and http requests are finished
    // https://github.com/angular/protractor/blob/master/docs/timeouts.md
    allScriptsTimeout: 60000,

    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 120000,
        isVerbose: true,
        print: function() {} // remove dots in reporter
    },

    onCleanUp: function (results) {
        retry.onCleanUp(results);
    },

    onPrepare: function() {
        const Jasmine2HtmlReporter = require('protractor-jasmine2-html-reporter');
        const SpecReporter         = require('jasmine-spec-reporter').SpecReporter;

        // Configuration:
        // https://github.com/bcaudan/jasmine-spec-reporter/blob/master/src/configuration.ts
        jasmine.getEnv().addReporter(new SpecReporter({
            colors: {
                enabled: colours
            },
            prefixes: {
                failed: "\u2715"
            },

        }));
        jasmine.getEnv().addReporter(new Jasmine2HtmlReporter({
            savePath: './reports/',
            screenshotsFolder: 'images',
            takeScreenshotsOnlyOnFailures: true
        }));

        retry.onPrepare();

        // browser.driver.manage().window().setSize(1440, 900);
        // browser.driver.manage().window().maximize();
    },

    afterLaunch: function() {
        return retry.afterLaunch(2);
    },



	plugins: [

	// https://www.npmjs.com/package/protractor-console
    //{
    //    package: 'protractor-console',
    //    logLevels: ['severe']
    //},

        // https://www.npmjs.com/package/protractor-console-plugin
       // https://github.com/angular/protractor-console-plugin/blob/master/spec/consoleFailFilterConfig.js

    {   package: 'protractor-console-plugin',
        failOnError: false,
        logWarnings: false,
        exclude: ['Failed blahbblah ... example',
                  /^.+Failed to load resource: the server responded with a status of 400 (Bad Request)+$/
        ]
	}]
};
```

```
npm list
prot.framework@1.0.0 D:\xyz
+-- array-unique@0.3.2
+-- checksum@0.1.1
| `-- optimist@0.3.7
|   `-- wordwrap@0.0.3
+-- debug@3.1.0
| `-- ms@2.0.0
+-- faker@4.1.0
+-- jasmine-spec-reporter@4.2.1
| `-- colors@1.1.2
+-- UNMET DEPENDENCY mssql@^4.1.0
+-- protractor-image-comparison@1.6.0
| +-- assert@1.4.1
| | `-- util@0.10.3
| |   `-- inherits@2.0.1
| +-- camel-case@3.0.0
| | +-- no-case@2.3.2
| | | `-- lower-case@1.1.4
| | `-- upper-case@1.1.3
| +-- fs-extra@1.0.0
| | +-- graceful-fs@4.1.11
| | +-- jsonfile@2.4.0
| | | `-- graceful-fs@4.1.11 deduped
| | `-- klaw@1.3.1
| |   `-- graceful-fs@4.1.11 deduped
| +-- png-image@1.1.1
| | +-- pngjs@3.3.2
| | `-- promise@6.1.0
| |   `-- asap@1.0.0
| `-- pngjs-image@0.11.7
|   +-- iconv-lite@0.4.19
|   +-- pako@0.2.9
|   +-- pngjs@2.3.1
|   +-- request@2.85.0
|   | +-- aws-sign2@0.7.0
|   | +-- aws4@1.6.0
|   | +-- caseless@0.12.0
|   | +-- combined-stream@1.0.6
|   | | `-- delayed-stream@1.0.0
|   | +-- extend@3.0.1
|   | +-- forever-agent@0.6.1
|   | +-- form-data@2.3.2
|   | | +-- asynckit@0.4.0
|   | | +-- combined-stream@1.0.6 deduped
|   | | `-- mime-types@2.1.18 deduped
|   | +-- har-validator@5.0.3
|   | | +-- ajv@5.5.2
|   | | | +-- co@4.6.0
|   | | | +-- fast-deep-equal@1.1.0
|   | | | +-- fast-json-stable-stringify@2.0.0
|   | | | `-- json-schema-traverse@0.3.1
|   | | `-- har-schema@2.0.0
|   | +-- hawk@6.0.2
|   | | +-- boom@4.3.1
|   | | | `-- hoek@4.2.1 deduped
|   | | +-- cryptiles@3.1.2
|   | | | `-- boom@5.2.0
|   | | |   `-- hoek@4.2.1 deduped
|   | | +-- hoek@4.2.1
|   | | `-- sntp@2.1.0
|   | |   `-- hoek@4.2.1 deduped
|   | +-- http-signature@1.2.0
|   | | +-- assert-plus@1.0.0
|   | | +-- jsprim@1.4.1
|   | | | +-- assert-plus@1.0.0 deduped
|   | | | +-- extsprintf@1.3.0
|   | | | +-- json-schema@0.2.3
|   | | | `-- verror@1.10.0
|   | | |   +-- assert-plus@1.0.0 deduped
|   | | |   +-- core-util-is@1.0.2
|   | | |   `-- extsprintf@1.3.0 deduped
|   | | `-- sshpk@1.14.1
|   | |   +-- asn1@0.2.3
|   | |   +-- assert-plus@1.0.0 deduped
|   | |   +-- bcrypt-pbkdf@1.0.1
|   | |   | `-- tweetnacl@0.14.5 deduped
|   | |   +-- dashdash@1.14.1
|   | |   | `-- assert-plus@1.0.0 deduped
|   | |   +-- ecc-jsbn@0.1.1
|   | |   | `-- jsbn@0.1.1 deduped
|   | |   +-- getpass@0.1.7
|   | |   | `-- assert-plus@1.0.0 deduped
|   | |   +-- jsbn@0.1.1
|   | |   `-- tweetnacl@0.14.5
|   | +-- is-typedarray@1.0.0
|   | +-- isstream@0.1.2
|   | +-- json-stringify-safe@5.0.1
|   | +-- mime-types@2.1.18
|   | | `-- mime-db@1.33.0
|   | +-- oauth-sign@0.8.2
|   | +-- performance-now@2.1.0
|   | +-- qs@6.5.1
|   | +-- safe-buffer@5.1.1
|   | +-- stringstream@0.0.5
|   | +-- tough-cookie@2.3.4
|   | | `-- punycode@1.4.1
|   | +-- tunnel-agent@0.6.0
|   | | `-- safe-buffer@5.1.1 deduped
|   | `-- uuid@3.2.1
|   +-- stream-buffers@1.0.1
|   `-- underscore@1.7.0
+-- protractor-jasmine2-html-reporter@0.0.7
| +-- async@2.6.0
| | `-- lodash@4.17.5 deduped
| +-- hat@0.0.3
| +-- lodash@4.17.5
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| `-- string.prototype.startswith@0.2.0
+-- protractor-retry@1.1.9
+-- q@1.5.1
+-- randomstring@1.1.5
| `-- array-uniq@1.0.2
+-- xml2js@0.4.19
| +-- sax@1.2.4
| `-- xmlbuilder@9.0.7
`-- yargs@11.0.0
  +-- cliui@4.0.0
  | +-- string-width@2.1.1 deduped
  | +-- strip-ansi@4.0.0
  | | `-- ansi-regex@3.0.0
  | `-- wrap-ansi@2.1.0
  |   +-- string-width@1.0.2
  |   | +-- code-point-at@1.1.0
  |   | +-- is-fullwidth-code-point@1.0.0
  |   | | `-- number-is-nan@1.0.1
  |   | `-- strip-ansi@3.0.1 deduped
  |   `-- strip-ansi@3.0.1
  |     `-- ansi-regex@2.1.1
  +-- decamelize@1.2.0
  +-- find-up@2.1.0
  | `-- locate-path@2.0.0
  |   +-- p-locate@2.0.0
  |   | `-- p-limit@1.2.0
  |   |   `-- p-try@1.0.0
  |   `-- path-exists@3.0.0
  +-- get-caller-file@1.0.2
  +-- os-locale@2.1.0
  | +-- execa@0.7.0
  | | +-- cross-spawn@5.1.0
  | | | +-- lru-cache@4.1.2
  | | | | +-- pseudomap@1.0.2
  | | | | `-- yallist@2.1.2
  | | | +-- shebang-command@1.2.0
  | | | | `-- shebang-regex@1.0.0
  | | | `-- which@1.3.0
  | | |   `-- isexe@2.0.0
  | | +-- get-stream@3.0.0
  | | +-- is-stream@1.1.0
  | | +-- npm-run-path@2.0.2
  | | | `-- path-key@2.0.1
  | | +-- p-finally@1.0.0
  | | +-- signal-exit@3.0.2
  | | `-- strip-eof@1.0.0
  | +-- lcid@1.0.0
  | | `-- invert-kv@1.0.0
  | `-- mem@1.1.0
  |   `-- mimic-fn@1.2.0
  +-- require-directory@2.1.1
  +-- require-main-filename@1.0.1
  +-- set-blocking@2.0.0
  +-- string-width@2.1.1
  | +-- is-fullwidth-code-point@2.0.0
  | `-- strip-ansi@4.0.0 deduped
  +-- which-module@2.0.0
  +-- y18n@3.2.1
  `-- yargs-parser@9.0.2
    `-- camelcase@4.1.0
```

**Comment by rafalf** [comment]
just found out

```
Windows as an environment to launch / use this package is not yet supported.
```

**Comment by rafalf** [comment]
not yet supported by windows
