### ISSUE TITLE
Travis problem

### ISSUE THREAD

**Issue by eromano** [yahoo/protractor-retry#45]
Hi guys ,
when I try to use it in protractor with a mac instance nodejs 8 configuration I receive this error at the end:

```sh
[10:42:33] E/launcher - Error: { Error: spawn EACCES
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at /home/travis/build/Alfresco/alfresco-ng2-components/node_modules/protractor-retry/lib/retry.js:151:38
    at Function.promise (/home/travis/build/Alfresco/alfresco-ng2-components/node_modules/q/q.js:682:9)
    at /home/travis/build/Alfresco/alfresco-ng2-components/node_modules/protractor-retry/lib/retry.js:150:18
    at Promise.apply (/home/travis/build/Alfresco/alfresco-ng2-components/node_modules/q/q.js:1165:26)
    at Promise.promise.promiseDispatch (/home/travis/build/Alfresco/alfresco-ng2-components/node_modules/q/q.js:788:41)
    at /home/travis/build/Alfresco/alfresco-ng2-components/node_modules/q/q.js:1391:14
    at runSingle (/home/travis/build/Alfresco/alfresco-ng2-components/node_modules/q/q.js:137:13)
    at flush (/home/travis/build/Alfresco/alfresco-ng2-components/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
[10:42:33] E/launcher - Process exited with error code 1
```
this is an example run:

https://travis-ci.org/Alfresco/alfresco-ng2-components/jobs/415831601

any idea or help?

**Comment by dreuxl** [comment]
After first look, I though it was the windows not supported issue, but no because u re not using on windows. 
unfortunately after first glance, I don't know.
Can it be a version issue of one the package u used vs the minimum ones we requires? the `q` package?

**Comment by dreuxl** [comment]
no tractions on this one
