### ISSUE TITLE
Error: spawn EACCES when test retry on Jenkins

### ISSUE THREAD

**Issue by rochan** [yahoo/protractor-retry#54]
13:00:20 [21:00:20] E/launcher - Error: { Error: spawn EACCES
13:00:20     at ChildProcess.spawn (internal/child_process.js:313:11)
13:00:20     at Object.exports.spawn (child_process.js:508:9)
13:00:20     at ui/node_modules/protractor-retry/lib/retry.js:151:38
13:00:20     at Function.promise (/ui/node_modules/q/q.js:702:9)
13:00:20     at /ui/node_modules/protractor-retry/lib/retry.js:150:18
13:00:20     at Promise.apply (/ui/node_modules/q/q.js:1185:26)
13:00:20     at Promise.promise.promiseDispatch (/ui/node_modules/q/q.js:808:41)
13:00:20     at /ui/node_modules/q/q.js:1411:14
13:00:20     at runSingle (/ui/node_modules/q/q.js:137:13)
13:00:20     at flush (/ui/node_modules/q/q.js:125:13) errno: 'EACCES', code: 'EACCES', syscall: 'spawn' }
13:00:20 [21:00:20] E/launcher - Process exited with error code 1
13:00:20 An unexpected error occurred: undefined

**Comment by dreuxl** [comment]
?

**Comment by Ashadeepa** [comment]
We still get this issue. Had this been resolved lately?
