### ISSUE TITLE
 TypeError: Cannot create property 'count' on string '[object Object]'

### ISSUE THREAD

**Issue by CarlosBolanos** [yahoo/protractor-retry#56]
hey..

As many of you, i have struggled with flaky tests for years and honestly I'm getting tired of it, and that is why i came up to your library, and i want to contribute, sadly i'm still unable to retry my tests.

and I'm getting the following error.
 **TypeError: Cannot create property 'count' on string '[object Object]'**

I'm intentionally triggering a failing test to force the retry.

**jasmine conf.**
`const SpecReporter = require('jasmine-spec-reporter').SpecReporter;
const retry = require('protractor-retry').retry;
const NUMBER_OF_RETRIES = 3;

exports.config = {
    framework: 'jasmine2',
    specs: 
   ['test/e2e/jasmine/fooSpec.js'],
    onPrepare: () => {
        retry.onPrepare();
        jasmine.getEnv().addReporter(new SpecReporter({
            suite: { displayNumber: true },
            spec: {
                displayErrorMessages: true,
                displayStacktrace: true,
                displaySuccessful: true,
            },
        }));
    },
    onCleanUp: function(results) {
        retry.onCleanUp(results);
    },
    afterLaunch: function() {
        return retry.afterLaunch(NUMBER_OF_RETRIES);
    },
};`

i started debugging the retry lib for a couple of hours and this is what i got.
retry.js
by the point i reach the function spawn(command, args), the params are 'properly' evaluated

`command =  node_modules/protractor/bin/protractor
args = [ [ 'test/e2e/jasmine/config.js' ],
  '--specs',
  'test/e2e/jasmine/fooSpec.js',
  '--retry',
  1,
  '--disableChecks',
  '--baseUrl',
  'http://localhost:9002',
  '--capabilities',
  { browserName: 'firefox',
    allScriptsTimeout: 40000,
    getPageTimeout: 40000,
    restartBrowserBetweenTests: true } 
]`;

capabilities is still a valid object to this point.
but when  the line var child = childProcess.spawn(command, args); execute. and a new instance of the protractor taskScheduler.js constructor file receives the following data.

`{ specs:
   [ 'test/e2e/jasmine/fooSpec.js' ],
  **multiCapabilities: [ '[object Object]' ],**
  verboseMultiSessions: false,
  rootElement: '',
  allScriptsTimeout: 11000,
  getPageTimeout: 10000,
  params: { ONE_DAY_SALE_PROPS: { OTH: [Object] } },
  framework: 'jasmine2',
  jasmineNodeOpts: { showColors: true, defaultTimeoutInterval: 30000 },
  seleniumArgs: [],
  mochaOpts: { ui: 'bdd', reporter: 'list' },
  configDir: '/Users/cbolanos/projects/fooProject/test/e2e/jasmine',
  noGlobals: false,
  plugins: [],
  skipSourceMapSupport: false,
  ng12Hybrid: false,
  onPrepare: [Function: onPrepare],
  onCleanUp: [Function: onCleanUp],
  afterLaunch: [Function: afterLaunch],
  _: [ 'test/e2e/jasmine/config.js' ],
  retry: 1,
  disableChecks: true,
  baseUrl: 'http://localhost:9002',
  **capabilities: '[object Object]',**
  '$0':
   '/usr/local/Cellar/node/11.9.0/bin/node ./node_modules/protractor/bin/protractor',
  unknownFlags_: [ 'retry' ] }`

you can see that capabilities and multicapabilities object has been stringified,
so i cant iterate config.multiCapabilities in the protractor/taskScheduler.js

this is the error I'm getting
TypeError: Cannot create property 'count' on string '[object Object]'
    at TaskScheduler.config.multiCapabilities.forEach (/Users/cbolanos/projects/Hotelwebapp/node_modules/protractor/built/taskScheduler.js:64:32)
    at Array.forEach (<anonymous>)
    at new TaskScheduler (/Users/cbolanos/projects/Hotelwebapp/node_modules/protractor/built/taskScheduler.js:40:34)
    at helper.runFilenameOrFn_.then.then.then (/Users/cbolanos/projects/Hotelwebapp/node_modules/protractor/built/launcher.js:175:25)
    at _fulfilled (/Users/cbolanos/projects/Hotelwebapp/node_modules/protractor/node_modules/q/q.js:834:54)
    at /Users/cbolanos/projects/Hotelwebapp/node_modules/protractor/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/Users/cbolanos/projects/Hotelwebapp/node_modules/protractor/node_modules/q/q.js:796:13)
    at /Users/cbolanos/projects/Hotelwebapp/node_modules/protractor/node_modules/q/q.js:604:44
    at runSingle (/Users/cbolanos/projects/Hotelwebapp/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/Users/cbolanos/projects/Hotelwebapp/node_modules/protractor/node_modules/q/q.js:125:13)
[17:18:28] E/launcher - Process exited with error code 1

so i think my problem is that for some reason the var child = childProcess.spawn(command, args); line is stringifing my capabilities.

**Comment by CarlosBolanos** [comment]
btw my child process contains the following data

{
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _closesNeeded: 3,
  _closesGot: 0,
  connected: false,
  signalCode: null,
  exitCode: null,
  killed: false,
  spawnfile: 'node_modules/protractor/bin/protractor',
  _handle:
   Process { onexit: [Function], pid: 46136, [Symbol(owner)]: [Circular] },
  spawnargs: [ 
       'node_modules/protractor/bin/protractor',
       [ 'test/e2e/jasmine/config.js' ],
       '--specs',
       'test/e2e/jasmine/fooSpec.js',
       '--retry',
       1,
       '--disableChecks',
       '--baseUrl',
       'http://localhost:9002',
       '--capabilities',
       { 
           browserName: 'firefox',
           allScriptsTimeout: 40000,
           getPageTimeout: 40000,
           restartBrowserBetweenTests: true 
        } 
  ],
  pid: 46136,
  stdin: Socket { ... },
  stdout: Socket { ... },
  stderr: Socket { ... },    
  stdio: [ Socket { ... }, Socket { ... }, Socket { ... } ] 
}

**Comment by CarlosBolanos** [comment]
confirmed that although the childProcess.stdout and stderr pass the capabilities to the process, on spwnargs.

protractor cli recive the process.argv  as a string 

`{
  title: 'node',
  version: 'v11.9.0',
  versions:
   { ....},
  arch: 'x64',
  platform: 'darwin',
  release:
   { .... },
  argv:
   [ '/usr/local/Cellar/node/11.9.0/bin/node',
     '/Users/cbolanos/projects/fooProject/node_modules/protractor/bin/p
rotractor',
     'test/e2e/jasmine/config.js',
     '--specs',
     '/Users/cbolanos/projects/fooProject/test/e2e/jasmine/details/cros
sSell/crossSell_spec.js',
     '--retry',
     '1',
     '--disableChecks',
     '--baseUrl',
     'http://localhost:9002',
     '--capabilities',
     **'[object Object]' ],**
  execArgv: [],
  env: { ... },
  pid: 47574,
  ppid: 47552,
  execPath: '/usr/local/Cellar/node/11.9.0/bin/node',
  debugPort: 9229,
  ......
}
`

**Comment by dreuxl** [comment]
Hi 
Thanks for trying to use the pkg!

2 questions before going forward:
* are u running your CMD from a windows machine.
* are u running the e2e Angular CLI for running your protractor cmd?
...  both cases are not supported yet.

**Comment by CarlosBolanos** [comment]
In my case is the grunt-protractor-runner on macos, and Jenkins  Linux jslave

**Comment by dreuxl** [comment]
ok, I m not sure what this wrapper is requesting and how it works behind the scene.
I would need to try myself to repro this issue

**Comment by CarlosBolanos** [comment]
I'm creating a sample project for you to run protractor-retry with grunt-protractor-runner and jasmine.
https://github.com/CarlosBolanos/angular-protractor-retry
