### ISSUE TITLE
Error: ReferenceError: Given is not defined

### ISSUE THREAD

**Issue by harmanpreetkaur58** [yahoo/protractor-retry#57]
I am new to protractor so i dont have much idea on this
can anyone help on the below mentioned error?

PS C:\Users\Scotts com\ProtractorAutomation> npm run cucumbertest

> ProtractorAutomation@ cucumbertest C:\Users\Scotts com\ProtractorAutomation
> protractor ./CucumberConfig.js

[13:02:44] I/launcher - Running 1 instances of WebDriver
[13:02:44] I/direct - Using ChromeDriver directly...

DevTools listening on ws://127.0.0.1:56647/devtools/browser/621fe841-90bd-40d0-a1e0-ae522d1881b1
[13:02:48] E/launcher - Error: ReferenceError: Given is not defined
    at Object.<anonymous> (C:\Users\Scotts com\ProtractorAutomation\StepDefinations\CalculatorSteps.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at supportCodePaths.forEach.codePath (C:\Users\Scotts com\ProtractorAutomation\node_modules\cucumber\lib\cli\index.js:142:42)
    at Array.forEach (<anonymous>)
    at Cli.getSupportCodeLibrary (C:\Users\Scotts com\ProtractorAutomation\node_modules\cucumber\lib\cli\index.js:142:22)
    at C:\Users\Scotts com\ProtractorAutomation\node_modules\cucumber\lib\cli\index.js:169:41
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Scotts com\ProtractorAutomation\node_modules\cucumber\lib\cli\index.js:44:103)
    at _next (C:\Users\Scotts com\ProtractorAutomation\node_modules\cucumber\lib\cli\index.js:46:194)
[13:02:48] E/launcher - Process exited with error code 100
npm ERR! code ELIFECYCLE
npm ERR! errno 100
npm ERR! ProtractorAutomation@ cucumbertest: `protractor ./CucumberConfig.js`
npm ERR! Exit status 100
npm ERR!
npm ERR! Failed at the ProtractorAutomation@ cucumbertest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Scotts com\AppData\Roaming\npm-cache\_logs\2019-03-14T02_02_48_146Z-debug.log

**Comment by dreuxl** [comment]
hi @harmanpreetkaur58 

Not sure I'm seeing `protractor-retry` in the picture here.

and look like you are running you protractor cmd from a windows machine, this OS is not yet supported by the pkg as mentioned in the README.
