### ISSUE TITLE
TypeError: Cannot read property 'pipe' of undefined

### ISSUE THREAD

**Issue by gil13** [yahoo/protractor-retry#63]
When its trying to re-execute failed test I always get this error

`[13:09:27] E/launcher - Error: TypeError: Cannot read property 'pipe' of undefined
    at /Users/alberto/agent/_work/1/s/node_modules/protractor-retry/lib/retry.js:152:26
    at Function.promise (/Users/alberto/agent/_work/1/s/node_modules/q/q.js:682:9)
    at /Users/alberto/agent/_work/1/s/node_modules/protractor-retry/lib/retry.js:150:18
    at Promise.apply (/Users/alberto/agent/_work/1/s/node_modules/q/q.js:1165:26)
    at Promise.promise.promiseDispatch (/Users/alberto/agent/_work/1/s/node_modules/q/q.js:788:41)
    at /Users/alberto/agent/_work/1/s/node_modules/q/q.js:1391:14
    at runSingle (/Users/alberto/agent/_work/1/s/node_modules/q/q.js:137:13)
    at flush (/Users/alberto/agent/_work/1/s/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)`

Any idea ?

**Comment by B1ll1** [comment]
I'm facing the same issue and what I could discover is that  the child_process.spawn() command is not generating the stdio so the stdout and stderr are not created. This way you get pipe of undefined.

I'm not sure exactly what is causing this but I could replicate it and it gives me the ENOENT or EACCESS error in this exact command.

**Comment by dreuxl** [comment]
yep, I m not sure how that case can happen. never seen it.

**Comment by kabomi** [comment]
Are you using angular-cli? I had a similar issue. You could try to run `protractor` instead of `ng`. Probably you will need to run your app from another console too.
